### ISSUE TITLE
Coregister of mri and label (label register is not good)

### ISSUE THREAD

**Issue by LarisaKozhekina** [jcreinhold/intensity-normalization#18]
Hello,
I am trying to make coregister to my dataset and use one of BRATS19 image as template. All images registered right but when i tried to register label with it i got it wrong. I think that label after coregister is not right or higher than mri image.
I also tried to use genericLabel for label images. Maybe i did it wrong?
`if 'mask' not in base: `
`         moved = ants.apply_transforms(template, input_img, mytx['fwdtransforms'], interpolator='nearestNeighbor')`
`if 'mask' in base:`
`         moved = ants.apply_transforms(template, input_img, mytx['fwdtransforms'], interpolator='genericLabel')` 

Images after coregister in MITK Workbench:
red is label and for 1 it is too smal. for 2 there must be no red.

![1](https://user-images.githubusercontent.com/16781515/78194366-a2dbaf00-7485-11ea-8d6a-e0a3c63cc7d1.PNG)
![2](https://user-images.githubusercontent.com/16781515/78194478-f1894900-7485-11ea-984d-ca95dab536ad.PNG)

What can be the problem? Or how can i register labels?

**Comment by jcreinhold** [comment]
Hi, @LarisaKozhekina. Thanks for your interest in this package. Please fill out the "Bug Report" form with all relevant information and I'll respond to that; either open a new issue or edit this issue such that it contains all of the bug report entries.

You must have deleted all of the form entries to create this issue, but I intentionally put those headers and questions in the bug report form so that I could quickly help users solve their problems.
