### ISSUE TITLE
T2 normalisation

### ISSUE THREAD

**Issue by 1alebra2** [jcreinhold/intensity-normalization#20]
## 📚 Documentation -- options
I have a slight problem:

T1 images are going through with fcn_normalize,

T2 and any other contrasts do not.

I use the following command line:

fcm-normalize -v -i testing/pat/pat_T2.nii.gz -o testing/full_fcm_test -m testing/pat/pat_BrainCerebellumMask.nii.gz -s -c t2 -tt csf

 

I get the following error: - intensity_normalization.exec.fcm_normalize - ERROR - stat: path should be string, bytes, os.PathLike or integer, not NoneType

Is does not matter if I cange the tissue type etc.  All works fine with T1. (which are the defaults)

I guess I do something wrong. Any help would be apppreciated. By the way, fcn does the csf segmentation, however produces a csf mask without the ventricles?

Any help on the command line is appreciated

**Comment by jcreinhold** [comment]
Hi @1alebra2. Thanks for your interest in this package. Please fill out the "Bug Report" form with all relevant information and I'll respond to that; either open a new issue or edit this issue such that it contains all of the bug report entries.

You must have deleted all of the form entries to create this issue, but I intentionally put those headers and questions in the bug report form so that I could quickly help users solve their problems.
