### ISSUE TITLE
fcn-normalize command line problem

### ISSUE THREAD

**Issue by 1alebra2** [jcreinhold/intensity-normalization#21]
## 🐛 Bug
Any arguments beyond T1 in the command line option -c  are not accepted for fcn-normalize

See below 

## Environment
the latest version on Linux.
I did both, installes the binaries and buildt it

## Additional context

T1 images are going through with fcn_normalize,
T2 and any other contrasts do not. 
I use the following command line:
fcm-normalize -v -i testing/pat/pat_T2.nii.gz-o testing/full_fcm_test -mtesting/pat/pat_BrainCerebellumMask.nii.gz -s -c t2 -tt csf
I get the following error: -intensity_normalization.exec.fcm_normalize - ERROR - stat: pathshould be string, bytes, os.PathLike or integer, not NoneType
Is does not matter if I cange the tissue type etc.  All worksfine with T1. (which are the defaults) 
 Any helpwould be apppreciated. Furthermore fcn-normalize does produces a csf mask without the ventricles when using csf as reference?

Any help  is appreciated

**Comment by jcreinhold** [comment]
FCM normalize works by first creating a tissue mask from the T1-w image. If you have a co-registered T2-w image, and you want to normalize that image, you can then use the tissue mask created as an input to `fcm-normalize` with the -tm option (as opposed to the -m option). Please refer to the [FCM normalization section of the tutorial](https://github.com/jcreinhold/intensity-normalization/blob/master/tutorials/5min_tutorial.md#fuzzy-c-means-based-normalization). This tutorial shows an example of how to use the `fcm-normalize` script. (I now see the tutorial is slightly out of date since it only refers to white matter (WM) masks, but the newest `fcm-normalize` supports more tissue masks than just WM masks. I'll update this soon, but the interface is the same except `-w` has been changed to `-tm`.)
