### ISSUE TITLE
python functions

### ISSUE THREAD

**Issue by giemmecci** [jcreinhold/intensity-normalization#33]
## 📚 Documentation

Hi, where can I find additional information on how to use the package using python functions? Thanks

**Comment by jcreinhold** [comment]
Hi, I'm in the process of refactoring this package so that it is easier to use the normalization methods as normal python functions. See [here](https://github.com/jcreinhold/intensity-normalization/tree/refactor) for the current refactor branch. It is almost complete, so please use it and let me know if you run into any bugs. I just tested Z-Score, WhiteStripe, FCM, LSQ, KDE, and Nyul on T1-w images and it worked as expected. It should be easier to use than the current version of the code with nibabel NIfTI images or numpy arrays.

You can install `intensity-normalization` from the refactor branch by doing: 

```bash
pip install git+git://github.com/jcreinhold/intensity-normalization.git@refactor
```

Then you can import, for example, the FCM normalizer with:

```python
from intensity_normalization.normalize.fcm import FCMNormalizer
fcm_norm = FCMNormalizer(tissue_type="wm")
import nibabel as nib
image = nib.load("test_t1w_image.nii")  # assume skull-stripped otherwise load mask too
normalized = fcm_norm(image) # alternatively, you can pass in a numpy array which will return a numpy array
normalized.to_filename("normalized_test_t1w_image.nii")
# or if you want to do further processing on the data array
norm_data = normalized.get_fdata()
# now normalize the co-registered, corresponding T2-w image
t2w_image = nib.load("test_t2w_image.nii")
t2w_normalized = fcm_norm(t2w_image, modality="t2")
```

Generally, the normalization methods have a similar interface, although some methods (RAVEL, Nyul, and LSQ) require a list of images (and, optionally, corresponding masks), like so:

```python
normalizer = NormalizerClass(init_args)
normalizer(image, mask, modality)
```

Where `image` is either a nibabel NIfTI image or a numpy array; `mask` is one of `None` (or not provided), a nibabel NIfTI image, or a numpy array; `modality` is a string representing the modality.

The documentation for this branch can be found [here](https://intensity-normalization.readthedocs.io/en/refactor/), although some of it will need to be cleaned up.

---

If you want to stick with the current version of the code, see the following links for examples/documentation.

[Tutorial section](https://github.com/jcreinhold/intensity-normalization/blob/master/tutorials/5min_tutorial.md#final-note)
[Documentation of Python functions](https://intensity-normalization.readthedocs.io/en/latest/normalization.html)

But I will no longer be supporting that version. All bug fixes will go to the refactor (v2.0.0) forward.

**Comment by jcreinhold** [comment]
Please re-open a separate issue if you run into a bug when using the package. If something is truly misleading in the documentation, please re-open this issue.

**Comment by giemmecci** [comment]
Thank you for the fast reply! I'll test the new branch.

We are very interested in the co-registration functionality and how to implement it in a python script.
We've had tons of issues with ANTsPy, while we found your documentation on the command-line usage very clear and were able to use it.

The main struggle was understanding how to replicate it as a python function; I see this is still absent in the documentation of the new branch (I've found [this](https://intensity-normalization.readthedocs.io/en/refactor/intensity_normalization.util.html#module-intensity_normalization.util.coregister)).

Do you have some examples or documentation on using the co-registration in python?

Thanks!

**Comment by jcreinhold** [comment]
FYI, I just pushed an update which fixed some bugs (mostly with the CLI) and also fixed the documentation. So refresh the documentation to see the latest version which should appear (at least slightly) more readable.

So, I still rely on ANTsPy to do registration, so if you're having trouble installing ANTsPy, you'll still need to figure out how to do that. It can be a bit painful unfortunately; you'll likely need to let it compile from source which requires CMake (if you're on a Mac, `brew install cmake` and then `pip install antspyx`).

Once you have ANTsPy installed, you can co-register an image like:

```python
# load the images
import nibabel as nib
image = nib.load("path/to/image.nii")
target = nib.load("path/to/target.nii")

# setup up registration
from intensity_normalization.util.coregister import register
transformation = "Affine"
interpolator = "bSpline"
initial_rigid = True  # do initial rigid transformation before transformation

# verify this is a supported transformation, interpolator
from intensity_normalization.type import (
    allowed_transformations, allowed_interpolators
)
assert transformation in allowed_transformations
assert interpolator in allowed_interpolators

# register the image to the target
registered = register(
    image, 
    target, 
    type_of_transform=transformation, 
    interpolator=interpolator,
    initial_rigid=initial_rigid
)

# save the image or get the registered image out
registered.to_filename("registered.nii")
registered_data = registered.get_fdata()
```

Alternatively, if you want to co-register many images to the same target, you can do:

```python
# setup up registration
from intensity_normalization.util.coregister import Registrator
transformation = "Affine"
interpolator = "bSpline"
initial_rigid = True

registrator = Registrator(
    target, 
    type_of_transform=transformation, 
    interpolator=interpolator,
    initial_rigid=initial_rigid
)

registered = registrator(image)
registered.to_filename("registered.nii")
registered_data = registered.get_fdata()

# or if you have many images
images = [nib.load(path_to_image) for path_to_image in image_paths]
registered_images = registrator.register_images(images)
```

Hope that helps. Please let me know if you run into any bugs in the new version! I've been delaying releasing it because I have no one to test it 😅

**Comment by giemmecci** [comment]
Thanks so much! This is very helpful, I'll be happy to test it together with others from our lab.

Yes, the main struggle with ANTsPy was actually just installing it, but I eventually made it and I was able to use your registration function on the command line.

You'll hear from us soon :) thanks again!
