### ISSUE TITLE
What is the "MD" modality? And other questions.

### ISSUE THREAD

**Issue by Siji-chl** [jcreinhold/intensity-normalization#55]
I wonder what md modality is, and the documentation should clarify that?

Best, chl

**Comment by jcreinhold** [comment]
MD is "mean diffusivity" a type of diffusion image.

I can add a note somewhere in the docs, but, in general, if you don't know what an option is, don't select it because it's probably not the right one for your use case.

Are you just wondering what MD is out of curiosity? Or did not knowing what MD is somehow impact your use of this package?

**Comment by jcreinhold** [comment]
Hey, thank you for the feedback, it's helpful. MD is a holdover from the original WhiteStripe implementation in R. I've never actually used it, but included it because the original authors did (although they also have FA, and I don't; I probably lost the FA option while refactoring.)

You're correct about how to use the tissue mask to normalize the contrast-enhanced T1-w image.

That warning is just a typo. Please update your version to v2.2.1 (pip install -U "intensity-normalization") to remove it.

Sorry about the `nib.load()` issue you ran into; I refactored the code in v2.2 from v2.1 to only accept array-like objects (e.g., a numpy array). I didn't get around to updating the tutorials, which I'm assuming you referenced, which caused you to assume they accepted nibabel images. That's my fault. Sorry again.

I updated the tutorials in this latest version, so check them out again (the difference in code is very small, essentially you just need to call `.get_fdata()` before passing it to the normalization function call).

Again, thank you for the feedback; it's very helpful! Sorry about the misleading documentation; it's just been very busy at work which kept me from getting around to updating it.

Please let me know if you run into any further errors or are confused about any of the documentation.

**Comment by Siji-chl** [comment]
Thank you! You help me a lot! I have updated the package to v2.2.1. The code runs successfully with numpy array using `.get_fdata()`. Thank you again!

However, when I used methods (such as KDE or WhiteStripe) which need to be specified `modality` parameter, it raised error 
`File "/home/xxx/Documents/py_environments/chl3.9/lib/python3.9/site-packages/intensity_normalization/util/histogram_tools.py", line 125, in get_tissue_mode
    modality_ = modality.value
AttributeError: 'str' object has no attribute 'value'`
I found that `modality` parameter does not accept `string` anymore (such as 't1') but `intensity_normalization.typing.Modality.T1` etc. Maybe it's a BUG or I was wrong about how to use it?

Thank you very much!
Best, chl

**Comment by Siji-chl** [comment]
By the way, in RAVEL method, `create_image_matrix_and_control_voxels` funtion requires that all images have the same shape with `assert all([shape == image_shape for shape in image_shapes])`. Why? 

Best, chl

**Comment by jcreinhold** [comment]
Hi @Siji-chl. Thanks again for the feedback. These are mistakes in the documentation and a bug, respectively 😓. Please update to version v2.2.2 and take a look at the updated documentation/tutorials.

RAVEL requires the images to be co-registered to extract the common "control voxels" (CSF), which is why there is an error, but I (optionally) handle the required registration in the function. (Note that the registration is only required to calculate the control voxels, so the original image shape, orientation, etc. should be returned.)

**Comment by jcreinhold** [comment]
Thanks again for the feedback!

**Comment by Siji-chl** [comment]
Wowwww! Your response is so fast! Thank you a lot!

But... I think there is another BUG in RAVEL method:joy: Look at `create_image_matrix_and_control_voxels` function, it creates a `image_matrix` numpy array with shape of `(image_size, n_images)`, and `image_size` is the number of voxel of the first image in the image list. So, if one of the subsequent images in the list has a larger number of voxel than that of the first image, it runs into error in **line 210 image_matrix[:, i - 1] = image_ws.flatten()** with `ValueError: could not broadcast input array from shape (5242880,) into shape (2801664,)`. (2801664 is the number of voxel of the first image in my image list, and 5242880 is a subsequent one.)

Best, chl

**Comment by jcreinhold** [comment]
😭 I was wrong when I said the assert was a bug. I forgot that the images *do* need to be the same size for the correction step.

In fact the images need to be deformably co-registered to get reliable results; however, empirically, it appears to work fine if the images are rigidly/affine co-registered.

I added an error message instead of the just the assert in v2.2.3! Although I revised ot after I released it, so the most accurate error message (and documentation for the args) is in the master branch and will be released with v2.2.4.

Thanks again!

**Comment by jcreinhold** [comment]
You need to at least rigidly or affine co-register the images.

**Comment by jcreinhold** [comment]
You can use the co-register script or Python class in intensity-normalization FWIW

**Comment by jcreinhold** [comment]
Deformable registration can be handled by RavelNormalize if the images are rigidly co-registered.

If you're application doesn't require your images to be co-registered at all, RAVEL is orobably not the right method for you, and you should use a different normalization method.

**Comment by jcreinhold** [comment]
Closing this since it seems like all your questions are answered. Please open a new issue if you run into a bug. If you have further general questions, can you use the discussion tab?

Thanks again for the feedback
