### ISSUE TITLE
`intensity-normalization` not working in Google Colab

### ISSUE THREAD

**Issue by EngSema** [jcreinhold/intensity-normalization#58]
Hi, 
Thank you first for your effort in this module.

I try to install intensity_normalization using Google colab notebook, but it seems not the whole package was installed.
When I try to import from intensity_normalization.typing, this error appears "No module named 'intensity_normalization.typing' ".

I try manually to add typing.py file to the package folder on my laptop, but unfortunately, I could not find the directory
  (/usr/local/lib/python3.7/dist-packages/intensity_normalization/__init__.py) on my laptop, although the packege is already installed and  

It is a weird issue! Anyway, can you help me with that 
I hope you can update the package with the typing.py file so I can install it again.
Thank you for your help.

![colab-error](https://user-images.githubusercontent.com/103286263/162526489-da6c35b6-acaf-4e8d-a403-a669e9de704e.PNG)

**Comment by jcreinhold** [comment]
I believe the issue here is that colab uses an old version of python (v3.7), so when you run `!pip install intensity-normalization` you're going to get the last version of the package that was compatible with the Colab version of python which isn't the latest version of `intensity-normalization` (so `typing` wasn't a module causing the error).

If you run: `!pip install "intensity-normalization==2.2.3"` (the latest version as of this issue), you'll receive an error (unless you've jury-rigged python v3.9 in colab) because that version isn't compatible with v3.7.

I had to drop support for older versions of python because I'm the only person maintaining this package and maintaining this package already takes too much time.

So, unfortunately, if you need to use colab, you'll have to generate the documentation for that version (run `import intensity_normalization; print(intensity_normalization.__version__)` to get the version) to get the correct module/function/class names, although the docs might be out-of-date depending which version you have to use. 

I can't support correcting documentation/bugs in old versions of the code though or adding support for older versions of Python; frankly, I wouldn't even accept a pull request to add support for older versions of Python because I'd probably be the one stuck maintaining it.

I'd strongly suggest just not using colab though, and using the latest version of the package which is only compatible with python v3.9 version (and greater once SimpleITK supports python v3.10).

If you use the latest version of the code and run into a bug, please open a separate issue!
