### ISSUE TITLE
Path issue in command line execution

### ISSUE THREAD

**Issue by jimcost** [jcreinhold/intensity-normalization#8]
I am attempting to execute `fcm-normalize` in the command window on a Kubuntu 18.04 LTS laptop.

Here is an example of the issue -
```bash
fcm-normalize -i t1n2mni.nii.gz -w fast_mni/ft1__pve_2.nii.gz -c t1 -o t1n2mni_fcm.nii.gz --single-img
```

```none
2019-02-13 11:54:33,707 - intensity_normalization.exec.fcm_normalize - ERROR - stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
  File "/home/jamie/miniconda3/lib/python3.7/site-packages/intensity_normalization-1.2.1-py3.7.egg/intensity_normalization/exec/fcm_normalize.py", line 124, in main
    if not os.path.isfile(args.image) or not os.path.isfile(args.brain_mask):
  File "/home/jamie/miniconda3/lib/python3.7/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType`
```

I attempted two more path formats for all the inputs with the same error. The other path formats were (1) ./t1n2mni.nii.gz and (2) /full/path/t1n2mni.nii.gz

**Comment by jcreinhold** [comment]
You need a brain mask to run`fcm-normalize`. You would change your call to:

```
fcm-normalize -i t1n2mni.nii.gz -m t1n2mni_brain_mask.nii.gz -c t1 -o t1n2mni_fcm.nii.gz --single-img
```

If you want to apply the `fcm-normalize` to other data, you would then run (e.g., a co-registered T2 image):

```
fcm-normalize -i t2n2mni.nii.gz -w fast_mni/wm_masks/ft1__pve_2.nii.gz -c t2 -o t1n2mni_fcm.nii.gz --single-img
```

Let me know if this solves your problem.

**Comment by jcreinhold** [comment]
I noticed that your error occurs on a line which corresponds to an older version of the code. Please update the code (i.e., uninstall and reinstall the package) before running the above commands. This should fix your problem.

**Comment by jimcost** [comment]
Thank you for replying. Followed both of the instructions, and I was able to get the code to execute. Two questions arise: (1) the WM mask created through `fcm-normalize` looks different than a WM mask (mask in yellow) -

![image](https://user-images.githubusercontent.com/6710629/52748095-d36f3980-2fa2-11e9-9f93-9c82aebb4b94.png)

(2) I pre-generated a WM mask using FSL, is it possible to include this mask as the -w parameter?

**Comment by jcreinhold** [comment]
Yikes! This type of output is possible since FCM can get stuck in a local optimum, but I have never encountered anything remotely like this; especially with a healthy brain image. 

Did you create the WM with that image? It looks like there is a brain mask on the image, but there are yellow voxels outside the brain mask. Is this the same brain mask used as input to `fcm-normalize`? Can you provide a picture of that same image without the overlay, I want to see if the yellow regions are the brightest spots in the image.

Also, this sounds stupid, but can you try running `fcm-normalize` again? Make sure that the image used to generate the WM mask is a T1-w image.

I think there is a bug in the single-img function with using a provided WM mask. I'll fix that within the next couple minutes.

**Comment by jimcost** [comment]
Code to create normalized T1w `fcm-normalize -i t1n.nii.gz -m t1ns_mask.nii.gz -c t1 -s -o fcm/`. Here `t1n` means a neck-stripped image and `t1ns_mask` means a brain-mask (or skull-removed `t1n` mask). Visualization code `mrview fcm/t1n_fcm.nii.gz -roi.load fcm/t1n_wmmask.nii.gz -mode 2`.

> Is this the same brain mask used as input to `fcm-normalize`?

No, I displayed the normalized version.

Same image without overlay:
![image](https://user-images.githubusercontent.com/6710629/52750385-54c9ca80-2fa9-11e9-9edd-25b717b38a09.png)

> Also, this sounds stupid, but can you try running `fcm-normalize` again? Make sure that the image used to generate the WM mask is a T1-w image.

The image sequence is a EFGRE3D. And I re-ran `fcm-normalize -i t1n.nii.gz -m t1ns_mask.nii.gz -c t1 -s -o fcm/` - outputting:

![image](https://user-images.githubusercontent.com/6710629/52750856-99099a80-2faa-11e9-9e13-0ca5ae98ce80.png)

Did that answer your questions? (Also, this is certainly a diseased brain.)

**Comment by jcreinhold** [comment]
Ah, I see the problem. The image is gadolinium enhanced, no? This won't work with my implementation. I didn't think to include this in the documentation, so thank you for providing this example. 

If you have a non-gadolinium-enhanced version of the image, please try `fcm-normalize` on that image. If the gad-enhanced image is co-registered to the non-gad-enhanced image, then you can use the WM mask provided from the latter on the former.

However, I'll also push a fix that will allow any WM mask to be used in a minute. I just need to run some tests.

**Comment by jcreinhold** [comment]
I pushed a fix which should allow you to use other WM masks, please do a fresh reinstall. 

Let me know if you encounter further problems and thank you for the feedback.

**Comment by jimcost** [comment]
Thank you, I will try it tomorrow.

Do you suspect fcm to fail with all gadolinium enhanced images, or simply
while generating the WM mask?

**Comment by jcreinhold** [comment]
Gadolinium-enhancement only affects the calculation of the WM mask.

If you aren't generating a WM mask with `fcm-normalize`, then there really isn't much of a point to use the script—except for convenience—since all `fcm-normalize` does is take the mean of the intensities inside the WM mask and divide the image by that value (and multiply by the `--norm-value` parameter). See [here](https://intensity-normalization.readthedocs.io/en/latest/algorithm.html#fuzzy-c-means) for a more thorough description.

Please let me know if you run into any problems running the script tomorrow though.

**Comment by jcreinhold** [comment]
The caveat is that the WM mask must be good. If you want to normalize a set of images consistently, then you do not want spurious contrast-enhanced regions in your WM mask which will throw off the calculation of the mean.

**Comment by jcreinhold** [comment]
Closing this as resolved. Please re-open/open another issue if you continue to encounter problems.
